### ISSUE TITLE
MsgInstallBundle does not work

### ISSUE THREAD

**Issue by 0xpatrickdev** [0xpatrickdev/agoric-gov-proposal-hub#2]
## Relevant Code: 
- `src/lib/messageBuilder.ts`
- `src/contexts/wallet.tsx` for stargateClient setup
- `src/App.tsx` for form/message submission 

### 1. Top Level `/agoric.swingset.MsgInstallBundle`, encoded to Unit8Array

```js
export const makeInstallBundleMsg = ({
  bundle,
  submitter,
}: MsgInstallArgs) => ({
  typeUrl: "/agoric.swingset.MsgInstallBundle",
  value: Uint8Array.from(
    MsgInstallBundle.encode(
      MsgInstallBundle.fromPartial({
        bundle,
        submitter: fromBech32(submitter).data,
      })
    ).finish()
  ),
});
```
Results in:
```bash
Error: Broadcasting transaction failed with code 7 (codespace: sdk). Log: Submitter address cannot be empty: invalid address
```

###  2. Top level `/agoric.swingset.MsgInstallBundle`, with bundle as just a string.

A la https://github.com/Agoric/agoric-sdk/blob/94c6b3c83a5326594f1e2886ae01d6a703a7a68f/packages/agoric-cli/src/publish.js#L270-L281

```js
export const makeInstallBundleMsg = ({ bundle, submitter }: MsgInstallArgs) => ({
  typeUrl: "/agoric.swingset.MsgInstallBundle",
  value: {
    bundle,
    submitter: fromBech32(submitter).data,
  },
});
```

Results in 400 Bad Request:
```json
{
  "jsonrpc": "2.0",
  "error": {
    "code": -32600,
    "message": "Invalid Request",
    "data": "error reading request body: http: request body too large"
  }
}
```

### 3. Wrapping in `/cosmos.tx.v1beta1.TxBody` , or `/cosmos.tx.v1beta1.Tx`. 

```js
import { Tx, TxBody } from "cosmjs-types/cosmos/tx/v1beta1/tx";
import Long from "long";

...

export const registry = new Registry([
  ...defaultRegistryTypes,
  // ["/cosmos.tx.v1beta1.Tx", Tx],
  // ["/cosmos.tx.v1beta1.TxBody", TxBody],
  ["/agoric.swingset.MsgInstallBundle", MsgInstallBundle],
]);

... 

export const makeInstallBundleMsg = ({ bundle, submitter }: MsgInstallArgs) => ({
  typeUrl: "/cosmos.tx.v1beta1.TxBody",
  value: {
    content: TxBody.encode({
      messages: [
        Any.fromPartial({
          typeUrl: "/agoric.swingset.MsgInstallBundle",
          value: Uint8Array.from(
            MsgInstallBundle.encode(
              MsgInstallBundle.fromPartial({
                bundle,
                submitter: fromBech32(submitter).data,
              })
            ).finish()
          ),
        }),
      ],
      memo: "",
      timeoutHeight: Long.fromNumber(99999999),
      extensionOptions: [],
      nonCriticalExtensionOptions: [],
    }).finish(),
  },
});
```

Don't have a log handy atm, but was running into 'not found in registry' errors for this. I am not sure how to define `MsgInstallBundle` as a child of `Tx` or `TxBody`.

**Comment by dckc** [comment]
[makeInteractiveSigner.js](https://github.com/Agoric/ui-kit/blob/main/packages/web-components/src/wallet-connection/makeInteractiveSigner.js) from ui-kit has a bunch of good stuff. `provisionSmartWallet` is a relevant precedent.

**Comment by 0xpatrickdev** [comment]
> [makeInteractiveSigner.js](https://github.com/Agoric/ui-kit/blob/main/packages/web-components/src/wallet-connection/makeInteractiveSigner.js) from ui-kit has a bunch of good stuff. `provisionSmartWallet` is a relevant precedent.

Agree, there is some good stuff here. "Amino" signing mode (vs direct) also produces human readable messages in keplr, which is important for trust/ux. 

I started that here: https://github.com/0xpatrickdev/agoric-gov-proposal-hub/compare/feat/amino-signer, but cannot get CoreEval working (signature mismatch error).  My current suspicion is an encoding error, perhaps more items need to be added here: https://github.com/cosmos/cosmjs/pull/1388/files#diff-192ab69af89db7725a39dffdc84bf9856750d3df3a9eda3fadd57e6a05dc6f28R87-R93

**Comment by 0xpatrickdev** [comment]
> You might try the `compressed_bundle` thing. [unbundle.js](https://gist.github.com/dckc/5eb31c216f4bf10e8f7a0ff82ced6108#file-unbundle-js) shows how to _decompress_ it; the reverse seems straightforward.

Had luck with this - thank you! `@agoric/cosmic-proto` could use a release if that's easily triggerable, but I checked in a patch for now. See https://github.com/0xpatrickdev/agoric-gov-proposal-hub/commit/e80f751fba3e4911f92d83aed3a744e44beedc6a

Tracking amino enhancements in #13

**Comment by turadg** [comment]
> @agoric/cosmic-proto could use a release if that's easily triggerable

There's a `dev` release on every commit to master. Try `yarn add @agoric/cosmic-proto@dev`. Then you can remove the patch.
