### ISSUE TITLE
toast messages

### ISSUE THREAD

**Issue by 0xpatrickdev** [0xpatrickdev/agoric-gov-proposal-hub#3]
add toast messages to show chain interactions (error, success)

**Comment by dckc** [comment]
in particular, on sign-and-submit
 - on success: give a link to the transaction on an explorer
     - or just the tx hash if no explorer is known for the selected network
 - on failure: display something reasonable
   - if there are diagnostics that might be too obscure for end-users to make sense of, help the user relay those diagnostics to support channels; for example, by copy-and-paste. Don't throw them away.

**Comment by dckc** [comment]
If we were planning a milestone for release to end users, I'd be inclined to re-phrase this as a bug an make it critical for the milestone.

**Comment by 0xpatrickdev** [comment]
the toast start before the wallet dialogue is confirmed, which is annoying. Maybe this can be fixed by using `sign` and `broadcast` instead of `signAndBroadcast` from stargateClient
