### ISSUE TITLE
balance can go stale when importing bundles

### ISSUE THREAD

**Issue by dckc** [0xpatrickdev/agoric-gov-proposal-hub#41]
1. connect wallet with no money
2. drop a bundle to upload - "insufficient balance" - so far so good
3. get more IST
4. still "insufficient balance" - not so good

**Comment by 0xpatrickdev** [comment]
Suggesting `30s` for api endpoint polling here: https://github.com/DCFoundation/cosmos-proposal-builder/pull/7

**Comment by 0xpatrickdev** [comment]
moved to https://github.com/DCFoundation/cosmos-proposal-builder/issues/9
