### ISSUE TITLE
Failed to change voting period: "message index"

### ISSUE THREAD

**Issue by dckc** [0xpatrickdev/agoric-gov-proposal-hub#43]
I can't seem to sign a proposal to change my local chain from 10s to 45s.

![image](https://github.com/0xpatrickdev/agoric-gov-proposal-hub/assets/150986/522ef028-5d3f-4612-bb6d-852f8d468910)

**Comment by 0xpatrickdev** [comment]
Right now only nanoseconds are supported, encoding support needs to be added for 's' 'm' and 'h'. See #36

**Comment by 0xpatrickdev** [comment]
`Failed to execute message; message index` seems to be another artifact of https://github.com/0xpatrickdev/agoric-gov-proposal-hub/blob/db60e9bc2e781d7227f6dd1401217593910a88c1/src/utils/transactionParser.tsx#L39-L45

Here is the full error message: 

<img width="372" alt="image" src="https://github.com/0xpatrickdev/agoric-gov-proposal-hub/assets/11021913/d0d64607-88a3-481b-9112-6205f5d61f36">


I am inclined to remove this block altogether, and show an uglier message for more detail. The current parsing works for things like "Title Missing", "Description missing", but it seems there may be a lot of cases to handle. What do you think? @dckc

**Comment by dckc** [comment]
yeah; peeking into error message text seems fraught with peril.

How about this for a strategy:
 - prevent most errors (e.g. Title Missing - change the UX to require a title)
 - for errors we're not set up to prevent, help the user relay detailed diagnostics to support (e.g. by copy-and-paste).
 
 To avoid the impression that the user should decipher the gobbledygook diagnostics, perhaps put a big **Failed to submit proposal** (or whatever it is that the user probably knows they were trying to do) and put the detailed diagnostic in `<small>` text.

**Comment by 0xpatrickdev** [comment]
Cool this sounds like a good approach. I completed the first suggestion here for a quick fix up: https://github.com/DCFoundation/cosmos-proposal-builder/pull/6

**Comment by 0xpatrickdev** [comment]
closing this with https://github.com/DCFoundation/cosmos-proposal-builder/pull/6 where this now shows:

<img width="333" alt="image" src="https://github.com/0xpatrickdev/agoric-gov-proposal-hub/assets/11021913/7d41405e-d913-497d-8951-56941b34cc45">

 tracking encoding in #36
