### ISSUE TITLE
gas and fee estimations

### ISSUE THREAD

**Issue by 0xpatrickdev** [0xpatrickdev/agoric-gov-proposal-hub#5]
determine how much each transaction will cost, and use that to populate the arguments for `signAndBroadcast`

**Comment by dckc** [comment]
I wonder about displaying current balances. But perhaps we can rely on Keplr to do that?

**Comment by 0xpatrickdev** [comment]
Tackled for bundles via #24, but may want to leave this open

**Comment by dckc** [comment]
Hm. I'd like us to clarify the scope if it's staying open. Tell me a story of how this could be done better?

Seems like installing bundles is the only tx with non-trivial fees... though... I don't have a good mental model of when an `agd` command needs `--gas=auto --gas-adjustment=1.2` and when it doesn't.

**Comment by dckc** [comment]
Ah... one thing to check: bundle uploads in a network where the validators charge >0 transaction fees. This has tripped me up a few times when going from emerynet to mainnet.

**Comment by 0xpatrickdev** [comment]
> Hm. I'd like us to clarify the scope if it's staying open. Tell me a story of how this could be done better?

![Screenshot 2023-11-06 at 1 30 22 PM](https://github.com/0xpatrickdev/agoric-gov-proposal-hub/assets/11021913/b95e4afb-08be-45bb-90ff-27668a6ea078)

I think this is just a matter of setting gas to auto, i think i had 18000[...] hardcoded somewhere before knowing this was an option. Alternatively, will look in the `simulate()` method available on stargate and deduce gas from that.
