### ISSUE TITLE
Include directory of well-known, parametrizable proposalTypes

### ISSUE THREAD

**Issue by 0xpatrickdev** [0xpatrickdev/agoric-gov-proposal-hub#8]
A user should be able to execute well known proposals, like addVault and startPSM, by entering relevant parameters in a form. Certain fields, like ibc/denom, could be referenced via cosmos/bank 

Ideally, the user should be able to select from among multiple versions of a proposal via a dropdown, and the app would pull from a well known or user provided git url.

**Comment by dckc** [comment]
The benefit of direct support for addVault and startPSM is clear.

The benefit of a more general mechanism is less clear.

The are active discussions for [DOT](https://community.agoric.com/t/dot-inter-protocol-vaults-collateral-onboarding-discussion/403) and [stkATOM](https://community.agoric.com/t/stkatom-inter-protocol-vaults-collateral-onboarding-discussion/517), in particular.

It's less clear clear when another startPSM proposal will come along.
